"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](ellipse_bg)\
$os\
$username\
$hostname\
[ ](ellipse_bg)\
[](ellipse_bg)\
$directory\
[ ](ellipse_bg)\
([](ellipse_bg)\
[ ](bg:ellipse_bg)\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
[ ](bg:ellipse_bg)\
[ ](ellipse_bg))\
$all\
"""

command_timeout = 3000
palette = 'tsuri_theme'

[palettes.tsuri_theme]
# ellipse_bg = "#1c223f" # dark blue variant
# ellipse_bg = "#242424" # dark grey variant
ellipse_bg = "#2E2E2E" # grey variant
# host_and_user_fg = "#609580"
host_and_user_fg = "#DDDDDD"
git_fg = "#F16B51"

[username]
show_always = true
style_user = "fg:host_and_user_fg bg:ellipse_bg"
style_root = "fg:#D44348 bg:ellipse_bg"
format = '[$user]($style)'

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "
format = '[$symbol($version(-$name) )]($style)'

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[cmake]
format = '[$symbol($version )]($style)'

[cmd_duration]
format = '~[$duration]($style) '

[conda]
symbol = " "
format = '[$symbol$environment]($style) '

[dart]
symbol = " "

[directory]
read_only = "󰌾 "
truncation_symbol = "…/"
truncate_to_repo = false
read_only_style = "bg:ellipse_bg"
style = "fg:#3EC669 bg:ellipse_bg"
format = "[$read_only]($read_only_style)[$path]($style)"

[docker_context]
symbol = " "
format = '[$symbol$context]($style) '

[dotnet]
format = '[$symbol($version )( $tfm )]($style)'

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "
style = "fg:git_fg bg:ellipse_bg"
format = '[$symbol$branch]($style) '

[git_branch]
symbol = " "
style = "fg:git_fg bg:ellipse_bg"
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_commit]
style = "fg:git_fg bg:ellipse_bg"
format = '[\( $hash$tag\)]($style)'

[git_state]
style = "fg:git_fg bg:ellipse_bg"
format = '\([ $state( $progress_current/$progress_total)]($style)\)'

[git_status]
style = "fg:git_fg bg:ellipse_bg"
conflicted = " = $count"
ahead = ' ⇡ $count'
behind = ' ⇣ $count'
diverged = " ⇕⇡$ahead_count⇣$behind_count"
untracked = "  $count"
stashed = "  $count"
modified = "  $count"
staged = "  $count"
renamed = "  $count"
deleted = " ✘ $count"
format = '[($all_status$ahead_behind)]($style)'

[golang]
symbol = " "
format = '[$symbol($version )]($style)'

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "
style = "fg:git_fg bg:ellipse_bg"
format = '[$symbol$branch(:$topic)]($style)'

[hostname]
ssh_symbol = " "
# ssh_only = false
style = "fg:host_and_user_fg bg:ellipse_bg"
format = '[ $ssh_symbol$hostname]($style)'

[java]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[julia]
symbol = " "

[kotlin]
symbol = " "
format = '[$symbol($version )]($style)'

[lua]
symbol = " "
format = '[$symbol($version )]($style)'

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "
format = '[$symbol$project]($style) '

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "
format = '[$symbol$state( \($name\))]($style) '

[nodejs]
symbol = " "
format = '[$symbol($version )]($style)'

[os]
style = "fg:host_and_user_fg bg:ellipse_bg"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "
style = "#3870A1"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "
format = '[$symbol($version )]($style)'

[scala]
symbol = " "
